      MODULE var
      IMPLICIT DOUBLE PRECISION (A-H, O-Z), INTEGER (I-N)  

C     COMMON FLFLFL      
      INTEGER ::    NCKW, NMCW, NEPS, NWT,NRE,NSCH,NX,NCON,NVISM,NTGV,
     1                NXGV, ND, NDKJ, NTDR, NYV, NSCL, NABV, NBLW, NBUF,
     2                NTWP, NS, NSN, NF, NFN, NDS, NSSV, NKA6, NA, ICKW,
     3                IMCW, IKS, ICC, IKR, IKI, IKP, IIP, LAC, LMK, 
     4                NEPA, NPD, NXNEW, NXINT,NSS,NYAVM,NXAVM,NCPM,NXT,
     5                NXR,LRW, LIW,IINFO,NZM,NDMIXP,NDGIVEN,NXXT,LENWP,
     6                LENIWP 
C     COMMON LOCS
      INTEGER :: NT, NM, NYS, NY, NTR, N_moments, NSM, NZ
C     COMMON VARS
      DOUBLE PRECISION :: CARBON, HYDRO

C     COMMON INDEXSP
      INTEGER :: iH, iH2, iOH, iCO, iPAH, iO2, iH2O
C     COMMON  OPTHICK       
      INTEGER :: NTBTEMP,NTBWN,NTABLE,NALFA,NSPACE, NDSRAD
C     COMMON  OPTHIN
      DOUBLE PRECISION :: SIGMA, SLEPS, TFXTM
      INTEGER :: IFXTM

      INTEGER :: LENRCK, LENICK

C     DATA SHARE BLOCK
      DOUBLE PRECISION :: TIMMX
      LOGICAL :: LZMIX,LUMESH,LHOM
    
      END MODULE var
