
      SUBROUTINE RESTRT (KK, NMAX, NATJ, JJ, LOUT, LMOLE, LBURNR, 
     1                   LUSTGV, NREAC, REAC, FLRT, NTEMP, XGIVEN,
     2                   TGIVEN, XSTR, XEND, ICKWRK, RCKWRK, EPS, 
     3                   JFIXT, TFIXT, X, S, NPROD, PROD, EPA)
C
C*****precision > double
        IMPLICIT DOUBLE PRECISION (A-H, O-Z), INTEGER (I-N)
C*****END precision > double
C
C*****precision > single
C        IMPLICIT REAL (A-H, O-Z), INTEGER (I-N)
C*****END precision > single
C
      COMMON /LOCS/ NT, NM, NYS, NY, NTR, N_moments, NSM
!      COMMON /LOCS/ NT, NM, NYS, NY, NTR
C
      DIMENSION REAC(*), ICKWRK(*), RCKWRK(*), EPS(*),
     1          XGIVEN(*), TGIVEN(*), X(*), S(NATJ, *),
     2          PROD(*), EPA(*)
C
      LOGICAL LMOLE, LBURNR, LUSTGV
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C INPUT-
C   KK     - NUMBER OF CHEMICAL SPECIES.
C   NMAX   - MAXIMUM NUMBER OF MESH POINTS.
C   NATJ   - NUMBER OF DEPENDENT VARIABLES AT EACH MESH POINT, AND
C            THE EXACT FIRST DIMENSION OF S(NATJ,*), SN(NATJ,*), AND
C            F(NATJ,*).  NATJ=KK+2.
C   JJ     - NUMBER OF MESH POINTS IN THE STARTING MESH.
C   LOUT   - UNIT NUMBER FOR PRINTED OUTPUT.
C   LMOLE  - IF LMOLE=.TRUE. THEN THE INPUT AND OUTPUT IS IN TERMS OF
C            MOLE FRACTIONS.
C   LUMESH - IF LUMESH=.TRUE. THEN A UNIFORM STARTING MESH IS USED.
C   LBURNR - IF LBURNR=.TRUE. THIS IS A BURNER STABILIZED FLAME PROBLEM.
C            IF LBURNR=.FALSE. THIS IS A FREELY PROPAGATING ADIABATIC
C            FLAME.
C   NREAC  - NUMBER OF REACTANT SPECIES SPECIFIED.
C   NINTM  - NUMBER OF INTERMEDIATE SPECIES SPECIFIED.
C   NPROD  - NUMBER OF PRODUCT SPECIES SPECIFIED.
C   REAC   - ARRAY OF REACTANT SPECIES INPUT MOLE (MASS) FRACTIONS.
C            DIMENSION REAC(*) AT LEAST KK.
C   XINTM  - ARRAY OF INTERMEDIATE SPECIES INPUT MOLE (MASS) FRACTIONS.
C            DIMENSION XINTM(*) AT LEAST KK.
C   PROD   - ARRAY OF PRODUCT SPECIES INPUT MOLE (MASS) FRACTIONS.
C            DIMENSION PROD(*) AT LEAST KK.
C   KR     - ARRAY OF CHEMKIN SPECIES INDICIES FOR THE REACTANTS AS
C            SPECIFIED IN THE REAC ARRAY.
C            DIMENSION KP(*) AT LEAST KK.
C   KI     - ARRAY OF CHEMKIN SPECIES INDICIES FOR THE INTERMEDIATES AS
C            SPECIFIED IN THE XINTM ARRAY.
C            DIMENSION KI(*) AT LEAST KK.
C   KP     - ARRAY OF CHEMKIN SPECIES INDICIES FOR THE PRODUCTS AS
C            SPECIFIED IN THE PROD ARRAY.
C            DIMENSION KP(*) AT LEAST KK.
C   FLRT   - THE MASS FLOW RATE IN A BURNER STABILIZED PROBLEM.
C              CGS UNITS - GM/(CM**2-SEC)
C   NTEMP  - THE NUMBER OF TEMPERATURE-POSITION PAIRS GIVEN FOR BURNER
C            STABILIZED PROBLEMS WHERE THE ENERGY EQUATION IS NOT
C            SOLVED, AND THE TEMPERATURES ARE INTERPOLATED FROM FIXED
C            PROFILES.
C   XGIVEN - THE DISTANCES FROM THE BURNER AT WHICH TEMPERATURES ARE
C            SPECIFIED.
C              DIMENSION XGIVEN(*) AT LEAST NTEMP.
C   TGIVEN - THE TEMPERATURES AT THE XGIVEN LOCATIONS.
C              DIMENSION TGIVEN(*) AT LEAST NTEMP.
C   XSTR   - BEGINNING X POSITION FOR THE MESH.
C              CGS UNITS - CM
C   XCEN   - X POSITION WHERE THE INITIAL STARTING ESTIMATES ARE
C            CENTERED.
C              CGS UNITS - CM
C   XEND   - ENDING POSITION FOR THE MESH.
C              CGS UNITS - CM
C   WMIX   - WIDTH OF THE MIXING REGION OVER WHICH THE STARTING
C            ESTIMATES ARE FIT.
C              CGS UNITS - CM
C   TFIXT  - TEMPERATURE THAT IS TO BE HELD FIXED FOR FREE FLAMES.
C              CGS UNITS - K
C
C WORK AND SCRATCH SPACE-
C   ICKWRK - INTEGER CHEMKIN WORK SPACE.
C   RCKWRK  - FLOATING POINT CHEMKIN WORK SPACE.
C   Y      - ARRAY OF MASS FRACTIONS.
C              DIMENSION Y(*) AT LEAST KK.
C   SI     - ARRAY OF THE SUM OF THE INTERMEDIATES.  USED FOR
C            DECREMENTING THE REACTANTS AND PRODUCTS TO KEEP
C            THE MOLE FRACTIONS SUMMED TO 1.
C              DIMENSION SI(*) AT LEAST JJ.
C
C OUTPUT-
C   EPS    - INLET MASS FLUX FRACTONS.
C              DIMENSION EPS(*) AT LEAST KK.
C   JFIXT  - MESH POINT THAT HAS A FIXED TEMPERATURE IN AN ADIABATIC
C            FLAME PROBLEM.
C   X      - STARTING MESH LOCATIONS.
C              DIMENSION X(*) AT LEAST JJ.
C   S      - STARTING SOLUTION ESTIMATES.  S(N,J) IS THE STARTING
C            ESTIMATE FOR COMPONENT N AT NODE J.
C              DIMENSION S(NATJ,*) EXACTLY NATJ FOR THE FIRST DIMENSION
C              AND AT LEAST JJ FOR THE SECOND.
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
cC
cC
cC        INITIALIZE MASS FLUX FRACTIONS TO 0.
cC
c      DO 100 K = 1, KK
c         EPS(K) = 0.0
c	   EPA(K) = 0.0
c100   CONTINUE
cC
cC         SHIFT THE SOLUTION TO THE RIGHT IF A NEW XSTR IS .LT. X(1)
cC
c      IF (XSTR .LT. X(1)) THEN
c         JJ = JJ + 1
c         IF (JJ .GT. NMAX) THEN
c            WRITE (LOUT, *) ' ERROR...NEW XSTR NEEDS TOO MANY POINTS'
c            STOP
c         ENDIF
c         DO 200 I = 2, JJ
c            J = JJ + 2 - I
c            X(J) = X(J-1)
c            DO 150 N = 1, NATJ
c               S(N,J) = S(N,J-1)
c150         CONTINUE
c200      CONTINUE
c         X(1) = XSTR
c         DO 300 N = 1, NATJ
c            S(N,1) = S(N,2)
c300      CONTINUE
c      ENDIF
cC
cC          IF A NEW XEND .GT. X(JJ), THEN ADD A POINT AT JJ+1
cC          IF A NEW XEND .LE. X(JJ), THEN REDUCE JJ, AND SET X(JJ)=XEND
cC
c      IF (XEND .GT. (X(JJ)+1.E-4) ) THEN
c         JJ = JJ + 1
c         IF (JJ .GT. NMAX) THEN
c            WRITE (LOUT, *) ' ERROR...NEW XEND NEEDS TOO MANY POINTS'
c            STOP
c         ENDIF
c         X(JJ) = XEND
c         DO 400 N = 1, NATJ
c            S(N,JJ) = S(N,JJ-1)
c400      CONTINUE
c      ELSE
cC         DO 500 J = 1, JJ
cC            IF (XEND .GE. X(J)) THEN
cC               X(J) = XEND
cC               GO TO 550
cC            ENDIF
cC500      CONTINUE
cC550      CONTINUE
cC         JJ = J
c      ENDIF
cC
cC             SET THE MASS FLUX FRACTION BOUNDARY CONDITIONS
cC
c      IF (LMOLE) THEN
c         CALL CKXTY (REAC, ICKWRK, RCKWRK, EPS)
c      ELSE
c         DO 1000 N = 1, NREAC
c            EPS(N) = REAC(N)
c1000     CONTINUE
c      ENDIF

cC
cC             SET THE SPECIES AMBIENT BOUNDARY CONDITIONS
cC
c      IF (LMOLE) THEN
c         CALL CKXTY (PROD, ICKWRK, RCKWRK, EPA)
c      ELSE
c         DO N = 1, NPROD
c            EPA(N) = PROD(N)
c         END DO
c      ENDIF

cC
cC        IF A NOT A BURNER, OVERWRITE FLRT FROM THE RESTART FILE.
cC           OTHERWISE, SET FLRT FROM THE NEW KEYWORD.
cC
c      IF (.NOT. LBURNR) FLRT = S(NM,1)
cC
cC        SET THE NEW FLOW RATE PROFILE  ???
cC
cC      DO 1200 J = 1, JJ
cC         S(NM,J) = FLRT
cC1200  CONTINUE
cC
cC         SET XGIVEN AND TGIVEN TO THE OLD SOLUTION
cC
c      IF (.NOT. LUSTGV) THEN
c         NTEMP = JJ
c         DO 1250 N = 1, NTEMP
c            XGIVEN(N) = X(N)
c            TGIVEN(N) = S(NT,N)
c1250     CONTINUE
c      ENDIF
cC
cC        FOR A FREE FLAME SET THE MESH POINT FOR THE FIXED TEMPERATURE.
cC        SINCE ON THE RESTART FILE, TFIXT MAY NOT EXACTLY EQUAL S(NT,J)
cC        WE CHECK FOR A POINT WITHIN 2K OF TFIXT, AND CHANGE TFIXT IF
cC        NECESSARY.
cC
c      IF (.NOT. LBURNR) THEN
c         DO 1300 J = 1, JJ
c            IF ( ABS(S(NT,J)-TFIXT) .LT. 2.0) THEN
c               JFIXT = J
c               TFIXT = S(NT,J)
c            ENDIF
c1300     CONTINUE
c      ENDIF
cC
c      RETURN
      END
C
C--------------------------------------------------------------------
